services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    restart: unless-stopped

    command:
      [
        "redis-server",
        "--requirepass",
        "${REDIS_PASSWORD}",
      ]

    volumes:
      - redis-data:/data

    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 5s
      retries: 10


  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
      args:
        DATABASE_URI: ${DATABASE_URI}

    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    restart: unless-stopped

    depends_on:
      - api

  nginx:
    image: macbre/nginx-http3:latest
    restart: unless-stopped

    depends_on:
      - web
      - api

    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

      # Сертификаты лежат на VPS
      - /var/certs/exora:/etc/nginx/ssl/exora:ro
      - /var/certs/api:/etc/nginx/ssl/api:ro


volumes:
  postgres-data:
  redis-data: