map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

upstream web_upstream {
    zone web_upstream 64k;

    # Встроенный DNS Docker
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    server web:3000 resolve;

    keepalive 32;
}

upstream api_upstream {
    zone api_upstream 64k;

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 5s;

    server api:4001 resolve;

    keepalive 32;
}