server {
    listen 80;

    server_name files.nicodes.ru;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen 443 quic;

    http2 on;

    server_name files.nicodes.ru;

    ssl_certificate     /etc/letsencrypt/live/files.nicodes.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/files.nicodes.ru/privkey.pem;

    add_header Alt-Svc 'h3=":443"; ma=86400' always;
    add_header QUIC-Status $http3 always;
    add_header Strict-Transport-Security "max-age=31536000" always;
    add_header X-Content-Encoding $sent_http_content_encoding always;
    add_header X-Content-Type-Options nosniff always;

    location / {
        root /srv/files;

        try_files $uri =404;

        autoindex off;

        # Разрешает нормально скачивать большие файлы частями.
        # Range requests Nginx поддерживает автоматически.
        sendfile on;

        # Кэш статики браузером
        expires 7d;
    }
}